foodbank/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ingredients.urls'))
]

ingredients/urls.py
from django.urls import path

from .views import recipe_by_ingredients, all_recipes, recipe_detail

urlpatterns = [
	path('', recipe_by_ingredients, name='recipe_by_ingredients'),
	path('recipes/', all_recipes, name='all_recipes'),
	path('recipes/<int:recipe_id>/', recipe_detail, name='recipe_detail')
]

ingredients/models.py
from django.db import models

# Create your models here.

ingredients/forms.py
from django import forms

class ByIngredients(forms.Form):
	ingredients = forms.CharField(max_length=200)

ingredients/views.py
from django.shortcuts import render, reverse, redirect
from .forms import ByIngredients
import dotenv, os, requests
from dotenv import load_dotenv
import random


load_dotenv()

keys = os.getenv('SPOONACULAR_API_KEY')

# Create your views here.
def recipe_by_ingredients(request):
	form = ByIngredients()
	context = {'form': form}
	return render(request, 'ingredients/search.html', {'form': form})

def all_recipes(request):
	form = ByIngredients(request.GET)
	if form.is_valid():
		ingredients = str(form.cleaned_data['ingredients'])
		# access Spoonacular API endpoint for recipes.
		if ingredients.strip() != '':
			ingredients_list = str(form.cleaned_data['ingredients']).split()
			# config API before sending
			uri = 'https://api.spoonacular.com/recipes/findByIngredients'
			params = {'apiKey': keys, 'ingredients': ingredients_list, 'number': '50'}
			
			# get the API response
			response = requests.get(uri, params=params)
			recipes = response.json()
			random.shuffle(recipes)
		else:
			recipes = []

	# pack up datas send for templates render
		context = {
				'recipes': recipes[:8],
				'form': form,
				}
		return render(request, 'ingredients/recipes.html', context)
	else:
		return redirect(reverse('recipe_by_ingredients'))

def recipe_detail(request, recipe_id):

	# recipe steps
	recipe_detail_endpoint = f'https://api.spoonacular.com/recipes/{recipe_id}/analyzedInstructions'
	
	params = {'apiKey': keys, "defaultCss":"true"}

	response = requests.get(recipe_detail_endpoint, params={'apiKey': keys})
	recipe_step = response.json()
	if recipe_step != []:
		steps = recipe_step[0]['steps']
	else:
		steps = ['There is no recipe yet!']

	# recipe ingredients
	info_endpoint = f'https://api.spoonacular.com/recipes/{recipe_id}/information'
	info = requests.get(info_endpoint, params={'apiKey': keys}).json()

	# get Ingredients Price Break Down Widget
	widget_header = {'accept': 'text/html'}

	# get Nutrition Break Down Widget
	nutrition_endpoint = f'https://api.spoonacular.com/recipes/{recipe_id}/nutritionWidget'
	nutrition_widget = requests.get(nutrition_endpoint, params=params, headers=widget_header).text

	context = {
		'image': f'https://spoonacular.com/recipeImages/{recipe_id}-556x370.jpg',
		'steps': steps,
		'info' : info,
		'nutrition_widget': nutrition_widget
	}

	return render(request, 'ingredients/recipe_detail.html', context)

templates/ingredients/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Food Ranger{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/food.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css" />
</head>
<body>
    
    {% block content %}
    {% endblock %}

    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>

templates/ingredients/footer.html
<footer>
	<div class="container">
	  
	  <div class="footer">
	    <hr>
	    <p>Copyright &copy; 2020</p>
	  </div>
	</div>
</footer>

templates/ingredients/nav.html
<nav class="header">
  <h1>
    <a href="{% url 'recipe_by_ingredients' %}" class="color"
      >FOOD RANGER</a
    >
  </h1>
  <i class="fas fa-bars bars show"></i>
  <i class="fas fa-times close"></i>
  <ul class="nav-bar">
    <li>
      <a href="https://spoonacular.com/food-api" class="color"
        >HELP</a
      >
    </li>
    <li>
      <a href="https://spoonacular.com/food-api/faq" class="color"
        >FAQ</a
      >
    </li>
    <li>
      <a href="https://spoonacular.com/contact" class="color"
        >CONTACT</a
      >
    </li>
  </ul>
</nav>

templates/ingredients/recipe_detail.html
{% extends 'ingredients/base.html' %}
{% load static %}


{% block title %}
{{ info.title }}
{% endblock %}

{% block content %}
<div class="bg-pattern" style="background-image: url({% static 'images/bg.jpg' %})">
    <section class="recipe-section">
      <div class="recipe-header">
        <div class="container">
          {% include 'ingredients/nav.html' %}
          <hr />
        </div>
      </div>
    </section>

    <section class="recipe-section">
      <div class="container">
        <div class="detail-layout">
          <div class="recipe-detail">
            <div class="recipe-title">
              <div class="title-text">
                <h2>{{ info.title }}</h2>
                <h4>Ingredients:</h4>
                <ul class="ingredients">
                  {% for ingredient in info.extendedIngredients %}
                  	<li>{{ ingredient.original }}</li>
                  {% endfor %}
                </ul>
              </div>
              <div class="title-image">
                <img src="{{ image }}" alt="" />
              </div>
            </div>
            <div class="intructions">
              <h4>Instructions:</h4>
              <ul>
              	{% for step in steps %}
                	<li><span>{{ step.number }}</span>{{step.step}}</li>
      			{% endfor %}
              </ul>
            </div>
          </div>

          <div class="nutrition-breakdown">{{ nutrition_widget | safe }}</div>
        </div>
      </div>
    </section>

    {% include 'ingredients/footer.html' %}

</div>
{% endblock %}

templates/ingredients/recipes.html
{% extends 'ingredients/base.html' %}

{% load static %}

{% block content %}
<div class="bg-pattern" style="background-image: url({% static 'images/bg.jpg' %})">
    <section class="recipe-section">
      <div class="recipe-header">
        <div class="container">
          {% include 'ingredients/nav.html' %}
          <div class="search">
            <form
              method="GET"
              action="{% url 'all_recipes' %}"
              class="recipe-search-form"
            >
              <input
                type="text"
                name="ingredients"
                maxlength="200"
                required
                id="id_ingredients"
                class="search-bar recipe-search-bar"
                placeholder="strawberry, ice scream, chocolate"
                value="{{ request.GET.ingredients }}"
              />
              <button type="submit" class="btn btn-sm">
                <i class="fa fa-search"></i>
              </button>
            </form>
          </div>
          <hr />
        </div>
      </div>
    </section>

    <!-- result -->
    <section recipe-section>
      <div class="container">
        <div class="grid-layout">
        	{% for recipe in recipes %}
	          <div class="recipe-container">
	            <div class="recipe-text">
	              <h3>{{ recipe.title|truncatewords:8 }}</h3>
	              <p><span>Missed Ingredients:</span>
	              	{% for miss in recipe.missedIngredients %}
	              		{{ miss.name }}{% if forloop.last %}.{% else %},{% endif %}
	              	{% empty %}
	              		None
	              	{% endfor %}
	          		</p>
	              <p><span>Unused Ingredients:</span>
	              	{% for unuse in recipe.unusedIngredients %}
	              		{{ unuse.name }}{% if forloop.last %}.{% else %},{% endif %}
	              	{% empty %}
	              		None
	              	{% endfor %}
	              </p>
	              <div>
	                <div class="border-btn"></div>
	                <a href="{% url 'recipe_detail' recipe.id %}" class="special-btn"
	                  >Learn More</a
	                >
	              </div>
	            </div>
	            <div class="recipe-image">
	              <img src="https://spoonacular.com/recipeImages/{{recipe.id}}-556x370.jpg" alt="" />
	            </div>
	          </div>
          	{% endfor %}
        </div>
      </div>
    </section>

    {% include 'ingredients/footer.html' %}
</div>
{% endblock %}

templates/ingredients/search.html
{% extends 'ingredients/base.html' %}
{% load static %}

{% block content %}
<section>
	<div class="search-page">
		<div class="container">
			<div><i class="fas"></i></div>
			<nav class="header">
				<h1><a href="{% url 'recipe_by_ingredients' %}">FOOD RANGER</a></h1>
				<ul class="nav-bar">
					<li><a href="https://spoonacular.com/food-api">HELP</a></li>
					<li><a href="https://spoonacular.com/food-api/faq">FAQ</a></li>
					<li><a href="https://spoonacular.com/contact">CONTACT</a></li>
				</ul>
			</nav>
			<div class="search">
				<div class="introduce-text">
					<h2>What's In Your <br> Fridge?</h2>
					<p>Ever wondered what recipes you can cook with the ingredients you have in your fridge or pantry? Find the best recipes for your next meal from our support</p>
				</div>
				<form method="GET" action="{% url 'all_recipes' %}" class="search-form">
					<input type="text" name="ingredients" maxlength="200" required id="id_ingredients" class="search-bar" placeholder="strawberry, ice scream, chocolate">
					<button type="submit" class="btn"><i class="fa fa-search"></i></button>
				</form>
			</div>
		</div>
	</div>
	<img src="{% static 'images/landing-page.jpg' %}" class="background-image">
</section>

{% endblock %}